name: Build & Push Docker Image

on:
  push:
    branches: [main]
  schedule:
    - cron: "0 6 * * 1"  # Weekly build on Monday 06:00 UTC

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: bsmeding/gitea-act-runner-ansible:latest

      - name: Update Docker Hub README
        uses: peter-evans/dockerhub-description@v4
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          repository: bsmeding/gitea-act-runner-ansible
          readme-filepath: ./README.md
          short-description: "Gitea runner container with Ansible"